# Generated by Django 5.1.7 on 2025-03-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('MUNICIPAL', 'municipal'), ('CITIZEN', 'citizen')], max_length=20),
        ),
    ]
