# Generated by Django 5.2 on 2025-04-03 05:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.CharField(choices=[('INFRASTRUCTURE', 'Infrastructure'), ('SERVICES', 'Services'), ('ENCROACHMENT', 'Encroachment'), ('OTHER', 'Other')], default='OTHER', max_length=15, verbose_name='Issue Type')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('IN PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=15, verbose_name='Status')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low'), ('NA', 'Not Applicable')], default='NORMAL', max_length=10, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='Reported By')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='issue_images/%Y/%m/%d/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Caption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='issues.issue', verbose_name='Issue')),
            ],
            options={
                'verbose_name': 'Issue Image',
                'verbose_name_plural': 'Issue Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
