# Generated by Django 5.1.7 on 2025-03-13 10:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('INFRASTRUCTURE', 'infrastructure'), ('ENCROACHMENT', 'encroachment'), ('SERVICES', 'services'), ('OTHER', 'other')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPETED', 'accepeted'), ('IN PROGRESS', 'in progress'), ('RESOLVED', 'resolved')], default='submitted', max_length=50)),
                ('priority', models.CharField(choices=[('HIGH', 'high'), ('NORMAL', 'normal'), ('LOW', 'low'), ('NA', 'na')], default='na', max_length=10)),
                ('reported_by', models.ForeignKey(default='nkadmin', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
